# Generated by Django 6.0.1 on 2026-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_options_newspost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='newspost',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл (MP4, MOV, AVI)', null=True, upload_to='news_videos/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='video_url',
            field=models.URLField(blank=True, help_text='Или укажите ссылку на YouTube/Vimeo', null=True, verbose_name='Ссылка на видео (YouTube/Vimeo)'),
        ),
    ]
