# Generated by Django 6.0.1 on 2026-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newspost_options_newspost_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='newspost',
            name='comment',
            field=models.TextField(blank=True, help_text='Внутренние заметки о новости (не публикуется в Telegram)', null=True, verbose_name='Комментарий/Заметки'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='video_url',
            field=models.URLField(blank=True, help_text='Или укажите ссылку на YouTube/Vimeo', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
