# Generated by Django 6.0.1 on 2026-01-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newspost_options_newspost_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='document',
            field=models.FileField(blank=True, help_text='PDF, Word, Excel, PowerPoint (макс. 50MB)', null=True, upload_to='news_documents/', verbose_name='Документ'),
        ),
    ]
